# using workflow from https://github.com/aguslr/bluevanilla/blob/main/.github/workflows/build.yml

name: Build image

on:
  # schedule:
  #   - cron: '20 20 * * *'  # 8:20pm everyday
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README*'
      - '*.md'
      - '*.png'
      - '*.txt'

  push:
    branches:
      - master
    paths-ignore:
      - 'README*'
      - '*.md'
      - '*.png'
      - '*.txt'

  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        fedora_version:
          - 42
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Docker
      #   uses: nxtcoder17/actions/setup-docker@main
      #   with:
      #     docker_registry: ${{ env.REGISTRY_URL }}
      #     docker_username: ${{ env.REGISTRY_USERNAME }}
      #     docker_password: ${{ env.REGISTRY_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build Image
        id: build_image
        shell: bash
        env:
          IMAGE: "ghcr.io/${{ github.repository}}:${{matrix.fedora_version}}"
        run: |+
          podman buildx build \
            -t $IMAGE -f ./Containerfile . --build-arg FEDORA_VERSION=${{ matrix.fedora_version }}
          podman push $IMAGE

      # - name: Build Image
      #   id: build_image
      #   shell: bash
      #   env:
      #     IMAGE: "ghcr.io/${{ github.repository}}:${{matrix.fedora_version}}"
      #     buildx_cache_master: "ghcr.io/${{ github.repository }}:buildx-cache-master"
      #     buildx_cache: "ghcr.io/${{ github.repository }}:buildx-cache-${{matrix.fedora_version}}"
      #   run: |+
      #     docker buildx build -t $IMAGE  -f ./Containerfile \
      #       --build-arg FEDORA_VERSION="${{ matrix.fedora_version }}" \
      #       --cache-to type=registry,ref="$buildx_cache",mode=max,compression=zstd,compression-level=13,force-compression=true \
      #       --cache-from type=registry,ref="$buildx_cache" \
      #       --cache-from type=registry,ref="$buildx_cache_master" \
      #       --output=type=image,compression=zstd,force-compression=true,compression-level=13,push=true \
      #       .

      # - name: Build Image
      #   id: build_image
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     containerfiles: |
      #       ./Containerfile
      #     tags: |
      #       ${{ steps.meta.outputs.tags }}
      #       ${{ steps.meta_pr.outputs.tags }}
      #       ${{ steps.meta_date.outputs.tags }}
      #       ${{ steps.meta_version.outputs.tags }}
      #       ${{ steps.meta_stable.outputs.tags }}
      #       ${{ steps.meta_latest.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     build-args: |
      #       FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
      #     oci: false

      # - name: Push to container registries
      #   uses: redhat-actions/push-to-registry@v2
      #   id: push
      #   with:
      #     tags: ${{ steps.build_image.outputs.tags }}
      #     extra-args: |
      #       --disable-content-trust

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v3.1.2
      #
      # - name: Sign container image
      #   run: |
      #     cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}@${TAGS}
      #   env:
      #     TAGS: ${{ steps.push.outputs.digest }}
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
      #     COSIGN_EXPERIMENTAL: false

      - name: Echo outputs
        run: |
          echo "IMAGE: ghcr.io/${{ github.repository}}:${{matrix.fedora_version}}"
